version: '3'
services:
  server:
    image: redash/redash:latest
    container_name: redash
    ports:
      - "5000:5000"
    environment:
      - REDASH_WEB_WORKERS=4
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2-alpine
    container_name: redash_postgres
    volumes:
      - /home/denis/Documents/CVBuild/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=redashpostgrespassword
      - POSTGRES_USER=redash
